version: '3.8'

services:
  fact-api:
    depends_on:
      - fact-database
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: hmctspublic.azurecr.io/fact/api:latest
    environment:
      # these environment variables are used by java-logging library
      - ROOT_APPENDER
      - JSON_CONSOLE_PRETTY_PRINT
      - ROOT_LOGGING_LEVEL
      - REFORM_SERVICE_TYPE
      - REFORM_SERVICE_NAME
      - REFORM_TEAM
      - REFORM_ENVIRONMENT
      - LOGBACK_DATE_FORMAT
      - LOGBACK_REQUIRE_THREAD
      - LOGBACK_REQUIRE_ALERT_LEVEL=false
      - LOGBACK_REQUIRE_ERROR_CODE=false
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fact-database:5432/fact
      - MAPIT_KEY=
    ports:
      - $SERVER_PORT:$SERVER_PORT
  fact-database:
    build:
      context: docker/database
    environment:
      POSTGRES_DB: fact
      POSTGRES_USER: fact
      POSTGRES_PASSWORD: fact
    ports:
      - 5432:5432
    volumes:
      - fact-database:/var/lib/postgresql/data

volumes:
  fact-database:
