java:
  postgresql:
    enabled: true
  initdbScripts:
    init.sql: |-
      CREATE EXTENSION IF NOT EXISTS cube WITH SCHEMA public;
      COMMENT ON EXTENSION cube IS 'data type for multidimensional cubes';
      CREATE EXTENSION IF NOT EXISTS earthdistance WITH SCHEMA public;
      COMMENT ON EXTENSION earthdistance IS 'calculate great-circle distances on the surface of the Earth';
COMMENT ON EXTENSION earthdistance IS 'calculate great-circle distances on the surface of the Earth';  environment:
    RUN_DB_MIGRATION_ON_STARTUP: true
    DB_OPTIONS:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
