CREATE TEMPORARY TABLE temporary_table
(
    courtSlug     character varying(250),
    postcode      character varying(250),
    region        character varying(250)
);

INSERT INTO temporary_table(courtSlug, postcode, region)
VALUES
  ('abergavenny-magistrates-court', 'NP7 5DL', 'South Wales East'),
  ('abergavenny-magistrates-court', 'NP20 4PR', 'South Wales East'),
  ('aberystwyth-justice-centre', 'SY23 1AS', 'Mid and West Wales'),
  ('administrative-court', 'WC2A 2LL', 'London'),
  ('admiralty-and-commercial-court', 'EC4A 1NL', 'London'),
  ('agricultural-land-and-drainage-first-tier-tribunal-property-chamber', 'M1 4AH', 'North West'),
  ('aldershot-justice-centre', 'GU11 1NY', 'South East'),
  ('aldershot-social-security-and-child-support-tribunal', 'SM1 1DA',	'London'),
  ('aldershot-social-security-and-child-support-tribunal', 'GU11 1EE', 'South East'),
  ('aldridge-magistrates-court', 'WS9 8NR', 'West Midlands'),
  ('aldridge-magistrates-court', 'WS2 8HA', 'West Midlands'),
  ('alton-magistrates-court', 'GU11 1NY', 'South East'),
  ('alton-magistrates-court', 'GU34 1DQ', 'South East'),
  ('amersham-law-courts', 'HP6 5AJ', 'South East'),
  ('andover-magistrates-court', 'SP10 1QP', 'South East'),
  ('andover-magistrates-court', 'GU11 1NY', 'South East'),
  ('ashford-tribunal-hearing-centre', 'TN23 1YB', 'South East'),
  ('avon-and-somerset-enforcement-department', 'BS23 9BE', 'South West'),
  ('avon-somerset-fixed-penalty-office', 'TA1 4WE', 'South West'),
  ('aylesbury-county-court-and-family-court', 'HP21 7QZ', 'South East'),
  ('aylesbury-crown-court', 'HP21 7FT', 'South East'),
  ('aylesbury-magistrates-court-and-family-court', 'HP21 7QZ', 'South East'),
  ('aylesbury-magistrates-court-and-family-court', 'MK9 2AJ', 'South East'),
  ('banbury-county-court', 'OX16 2AW', 'South East'),
  ('banbury-fixed-penalty-office', 'OX16 9PR', 'South East'),
  ('banbury-magistrates-court', 'OX16 2AW', 'South East'),
  ('banbury-magistrates-court', 'OX1 1RZ', 'South East'),
  ('bankruptcy-court-high-court', 'EC4A 1NL', 'London'),
  ('barkingside-magistrates-court', 'IG6 1HW', 'London'),
  ('barkingside-magistrates-court', 'E3 4DJ', 'London'),
  ('barnet-civil-and-family-courts-centre', 'N3 1BQ', 'London'),
  ('barnsley-law-courts', 'S70 2HW', 'Yorkshire and the Humber'),
  ('barnsley-social-security-and-child-support-tribunal', 'S70 1WA', 'Yorkshire and the Humber'),
  ('barnsley-social-security-and-child-support-tribunal', 'LS1 2ED', 'Yorkshire and the Humber'),
  ('barnstaple-crown-court', 'EX1 1UH', 'South West'),
  ('barnstaple-crown-court', 'EX31 1DX', 'South West'),
  ('barnstaple-magistrates-county-and-family-court', 'EX31 1DU', 'South West'),
  ('barrow-in-furness-county-court-and-family-court', 'LA14 5QX', 'North West'),
  ('barrow-in-furness-magistrates-court', 'LA14 5QX', 'North West'),
  ('basildon-combined-court', 'SS14 2EW', 'Eastern'),
  ('basildon-magistrates-court-and-family-court', 'SS14 1EH', 'Eastern'),
  ('basildon-magistrates-court-and-family-court', 'CM1 9PZ', 'Eastern'),
  ('basingstoke-county-court-and-family-court', 'RG21 4AB', 'South East'),
  ('basingstoke-magistrates-court', 'RG21 4AB', 'South East'),
  ('bath-law-courts-civil-family-and-magistrates', 'BA1 5AF', 'South West'),
  ('bedford-county-court-and-family-court', 'MK40 1SQ', 'Eastern'),
  ('bedford-county-court-and-family-court', 'LU1 2LJ', 'Eastern'),
  ('bedford-tribunal-hearing-centre', 'MK40 3HS', 'Eastern'),
  ('belmarsh-magistrates-court', 'BR1 1RA', 'London'),
  ('berwick-upon-tweed-magistrates-court', 'TD15 1DX', 'North East'),
  ('berwick-upon-tweed-magistrates-court', 'NE1 3LA', 'North East'),
  ('beverley-magistrates-court-and-hearing-centre', 'HU17 9EJ', 'Yorkshire and the Humber'),
  ('bexley-magistrates-court', 'DA6 7ND', 'London'),
  ('bexley-magistrates-court', 'BR1 1RA', 'London'),
  ('bexleyheath-social-security-and-child-support-tribunal', 'DA7 4EG', 'London'),
  ('bexleyheath-social-security-and-child-support-tribunal', 'SM1 1DA', 'London'),
  ('bicester-magistrates-court-and-family-court', 'OX26 2NZ', 'South East'),
  ('bicester-magistrates-court-and-family-court', 'OX1 1RZ', 'South East'),
  ('birkenhead-county-court', 'CH41 5EN', 'North West'),
  ('birmingham-civil-and-family-justice-centre', 'B4 6DS', 'West Midlands'),
  ('birmingham-crown-court', 'B4 7NA', 'West Midlands'),
  ('birmingham-district-probate-registry', 'B4 6DU', 'West Midlands'),
  ('birmingham-immigration-and-asylum-chamber-first-tier-tribunal', 'B4 6DS', 'West Midlands'),
  ('birmingham-magistrates-court', 'B4 6QA', 'West Midlands'),
  ('birmingham-social-security-and-child-support-tribunal', 'B16 6FR', 'West Midlands'),
  ('birmingham-youth-court', 'B4 6QA', 'West Midlands'),
  ('blackburn-family-court', 'BB1 6DJ', 'North West'),
  ('blackburn-magistrates-court', 'BB2 1AA', 'North West'),
  ('blackfriars-crown-court', 'SE1 0BT', 'London'),
  ('blackpool-family-court', 'FY1 5RJ', 'North West'),
  ('blackpool-magistrates-and-civil-court', 'FY1 5DQ', 'North West'),
  ('blackwood-civil-and-family-court', 'NP12 1NY', 'South Wales East'),
  ('bodmin-county-court-and-family-court', 'PL31 2AL', 'South West'),
  ('bodmin-magistrates-court', 'PL31 2AL', 'South West'),
  ('bodmin-probate-sub-registry', 'PL31 2AL', 'South West'),
  ('bodmin-probate-sub-registry', 'CF24 0RZ', 'South Wales Central'),
  ('bolton-county-court-and-family-court', 'BL1 1SU', 'North West'),
  ('bolton-crown-court', 'BL1 1SU', 'North West'),
  ('bolton-magistrates-court', 'BL1 1SU', 'North West'),
  ('bolton-social-security-and-child-support-tribunal', 'BL1 2HB', 'North West'),
  ('bolton-social-security-and-child-support-tribunal', 'L2 5UZ', 'North West'),
  ('boston-county-court-and-family-court', 'PE21 6PE', 'East Midlands'),
  ('boston-county-court-and-family-court', 'LN5 7PS', 'East Midlands'),
  ('boston-magistrates-court', 'PE21 6PE', 'East Midlands'),
  ('boston-magistrates-court', 'LN5 7QA', 'East Midlands'),
  ('bournemouth-and-poole-county-court-and-family-court', 'BH7 7DS', 'South West'),
  ('bournemouth-crown-court', 'BH7 7DS', 'South West'),
  ('bournemouth-magistrates-court', 'BH1 1JH', 'South West'),
  ('bradford-and-keighley-magistrates-court-and-family-court', 'BD1 1LA', 'Yorkshire and the Humber'),
  ('bradford-combined-court-centre', 'BD1 1JA', 'Yorkshire and the Humber'),
  ('bradford-tribunal-hearing-centre', 'BD3 7BH', 'Yorkshire and the Humber'),
  ('brentford-county-and-family-court', 'TW8 0JJ', 'London'),
  ('bridlington-magistrates-court-and-hearing-centre', 'YO16 4EJ', 'Yorkshire and the Humber'),
  ('brighton-county-court', 'BN2 0RF', 'South East'),
  ('brighton-district-probate-registry', 'BN2 0RF', 'South East'),
  ('brighton-hearing-centre', 'BN2 0JD', 'South East'),
  ('brighton-hearing-centre', 'BN2 0RF', 'South East'),
  ('brighton-magistrates-court', 'BN2 0LG', 'South East'),
  ('brighton-tribunal-hearing-centre', 'BN3 1TL', 'South East'),
  ('brighton-tribunal-hearing-centre', 'BD3 7BH', 'Yorkshire and the Humber'),
  ('bristol-civil-and-family-justice-centre', 'BS1 6GR', 'South West'),
  ('bristol-crown-court', 'BS1 1DA', 'South West'),
  ('bristol-district-probate-registry', 'CF24 0RZ', 'South Wales Central'),
  ('bristol-magistrates-court-and-tribunals-hearing-centre', 'BS1 3NU', 'South West'),
  ('bristol-social-security-and-child-support-tribunal', 'CF24 0AB', 'South Wales Central'),
  ('bristol-social-security-and-child-support-tribunal', 'BS1 2BD', 'South West'),
  ('bromley-county-court-and-family-court', 'BR1 3PX', 'London'),
  ('bromley-magistrates-court', 'BR1 1RA', 'London'),
  ('burnley-combined-court-centre', 'BB11 1XD', 'North West'),
  ('burnley-magistrates-court', 'BB11 2BS', 'North West'),
  ('burnley-magistrates-court', 'BB2 1AA', 'North West'),
  ('burton-upon-trent-magistrates-court', 'ST16 3DW', 'West Midlands'),
  ('bury-and-rochdale-magistrates-court', 'BL9 0HX', 'North West'),
  ('bury-county-court', 'BL9 0HX', 'North West'),
  ('bury-st-edmunds-county-court-and-family-court', 'NR3 1UR', 'Eastern'),
  ('bury-st-edmunds-county-court-and-family-court', 'IP33 1TR', 'Eastern'),
  ('bury-st-edmunds-crown-court', 'IP33 1HF', 'Eastern'),
  ('bury-st-edmunds-regional-divorce-centre', 'IP33 1TR', 'Eastern'),
  ('buxton-county-court', 'DE1 2XE', 'East Midlands'),
  ('caernarfon-justice-centre', 'LL55 2DF', 'North Wales'),
  ('caernarfon-probate-sub-registry', 'CF24 0RZ', 'South Wales Central'),
  ('caernarfon-probate-sub-registry', 'LL55 2DF', 'North Wales'),
  ('camberwell-green-magistrates-court', 'BR1 1RA', 'London'),
  ('camberwell-green-magistrates-court', 'SE5 7UP', 'London'),
  ('cambridge-county-court-and-family-court', 'PE1 1EJ', 'Eastern'),
  ('cambridge-county-court-and-family-court', 'CB1 1BA', 'Eastern'),
  ('cambridge-crown-court', 'CB1 1BT', 'Eastern'),
  ('cambridge-magistrates-court', 'CB2 3AX', 'Eastern'),
  ('cambridge-magistrates-court', 'PE1 1ED', 'Eastern'),
  ('cannock-magistrates-court', 'WS11 1AT', 'West Midlands'),
  ('cannock-magistrates-court', 'ST16 2QQ', 'West Midlands'),
  ('canterbury-combined-court-centre', 'CT1 1ZA', 'South East'),
  ('canterbury-magistrates-court', 'CT20 2DH', 'South East'),
  ('canterbury-magistrates-court', 'CT1 2UE', 'South East'),
  ('cardiff-civil-and-family-justice-centre', 'CF10 1ET', 'South Wales Central'),
  ('cardiff-crown-court', 'CF10 3PG', 'South Wales Central'),
  ('cardiff-magistrates-court', 'CF24 0RZ', 'South Wales Central'),
  ('cardiff-probate-registry-of-wales', 'CF24 0RZ', 'South Wales Central'),
  ('cardiff-social-security-and-child-support-tribunal', 'CF24 0AB', 'South Wales Central'),
  ('care-standards-tribunal', 'DL1 1RU', 'North East'),
  ('carlisle-combined-court', 'CA1 1DJ', 'North West'),
  ('carlisle-magistrates-court', 'CA3 8QH', 'North West'),
  ('carlisle-probate-sub-registry', 'NE1 4DR', 'North East'),
  ('carmarthen-county-court-and-family-court', 'SA15 3AL', 'Mid and West Wales'),
  ('carmarthen-county-court-and-family-court', 'SA31 3BT', 'Mid and West Wales'),
  ('carmarthen-probate-sub-registry', 'CF24 0RZ', 'South Wales Central'),
  ('carmarthen-probate-sub-registry', 'SA31 3BT', 'Mid and West Wales'),
  ('central-criminal-court', 'EC4M 7EH', 'London'),
  ('central-family-court', 'WC1V 6NP', 'London'),
  ('central-london-county-court-bankruptcy', 'WC2A 2LL', 'London'),
  ('central-london-county-court', 'WC2A 2LL', 'London'),
  ('central-london-employment-tribunal', 'WC2B 6EX', 'London'),
  ('centralised-attachment-of-earnings-payments-caps', 'NN1 2LH', 'East Midlands'),
  ('chancery-division', 'EC4A 1NL', 'London'),
  ('chelmsford-county-and-family-court', 'CM2 0PP', 'Eastern'),
  ('chelmsford-crown-court', 'CM1 1EL', 'Eastern'),
  ('chelmsford-magistrates-court-and-family-court', 'CM1 9PZ', 'Eastern'),
  ('chelmsford-magistrates-court-and-family-court', 'CM1 1NT', 'Eastern'),
  ('cheltenham-magistrates-court', 'GL50 3PF', 'South West'),
  ('cheltenham-magistrates-court', 'GL1 2XG', 'South West'),
  ('cheshire-and-merseyside-central-payment-and-enforcement-centre', 'WA7 9DU', 'North West'),
  ('chester-civil-and-family-justice-centre', 'CH1 1SN', 'North West'),
  ('chester-crown-court', 'CH1 2AN', 'North West'),
  ('chester-le-street-magistrates-court', 'DH3 3UA', 'North East'),
  ('chester-magistrates-court', 'CH1 2XA', 'North West'),
  ('chester-probate-sub-registry', 'L2 1XA', 'North West'),
  ('chesterfield-county-court', 'S41 7TW', 'East Midlands'),
  ('chichester-combined-court-centre', 'PO19 1SX', 'South East'),
  ('chippenham-and-trowbridge-law-courts', 'SN15 3BF', 'South West'),
  ('chorley-magistrates-court', 'PR7 1RZ', 'North West'),
  ('chorley-magistrates-court', 'PR1 2QT', 'North West'),
  ('city-of-london-magistrates-court', 'EC4N 4XY', 'London'),
  ('city-of-london-magistrates-court', 'NW1 5BR', 'London'),
  ('civil-money-claims-service-centre', 'CM20 9RA', 'Eastern'),
  ('claim-production-centre-cpc', 'NN1 2LH', 'East Midlands'),
  ('clerkenwell-and-shoreditch-county-court-and-family-court', 'EC1V 3RE', 'London'),
  ('cleveland-durham-northumbria-and-north-yorkshire-central-enforcement-unit', 'NE29 1DZ', 'North East'),
  ('colchester-county-court-and-family-court', 'CO3 3EG', 'Eastern'),
  ('colchester-magistrates-court-and-family-court', 'CO2 7EF', 'Eastern'),
  ('colchester-magistrates-court-and-family-court', 'CM1 9PZ', 'Eastern'),
  ('corby-magistrates-court', 'NN3 6AS', 'East Midlands'),
  ('county-court-business-centre-ccbc', 'NN1 2LH', 'East Midlands'),
  ('county-court-money-claims-centre-ccmcc', 'M5 0BY', 'North West'),
  ('court-of-appeal-civil-division', 'WC2A 2LL', 'London'),
  ('court-of-appeal-criminal-division', 'WC2A 2LL', 'London'),
  ('court-of-protection', 'WC1A 9JA', 'London'),
  ('coventry-combined-court-centre', 'CV1 2SN', 'West Midlands'),
  ('coventry-magistrates-court', 'CV1 2SQ', 'West Midlands'),
  ('crawley-magistrates-court', 'RH10 8BF', 'South East'),
  ('crawley-magistrates-court', 'BN2 0LG', 'South East'),
  ('crewe-county-court-and-family-court', 'CW1 2DP', 'North West'),
  ('crewe-south-cheshire-magistrates-court', 'CW1 2DT', 'North West'),
  ('croydon-county-court-and-family-court', 'CR9 5AB', 'London'),
  ('croydon-crown-court', 'CR9 5AB', 'London'),
  ('croydon-employment-tribunal', 'CR0 2RF', 'London'),
  ('croydon-magistrates-court', 'CR9 3NG', 'London'),
  ('croydon-magistrates-court', 'BR1 1RA', 'London'),
  ('cwmbran-magistrates-court', 'NP44 3YA', 'South Wales East'),
  ('cwmbran-magistrates-court', 'NP20 4PR', 'South Wales East'),
  ('darlington-county-court-and-family-court', 'DL3 7RG', 'North East'),
  ('darlington-county-court-and-family-court', 'DL3 7RL', 'North East'),
  ('darlington-magistrates-court-and-family-court', 'DL1 1RU', 'North East'),
  ('darlington-magistrates-court-and-family-court', 'DL5 5RT', 'North East'),
  ('dartford-county-court-and-family-court', 'DA1 1DX', 'South East'),
  ('derby-combined-court-centre', 'DE1 2XE', 'East Midlands'),
  ('derby-magistrates-court', 'DE1 3JR', 'East Midlands'),
  ('derby-social-security-and-child-support-tribunal', 'DE1 3JR', 'East Midlands'),
  ('derby-social-security-and-child-support-tribunal', 'B16 6FR', 'West Midlands'),
  ('devon-and-cornwall-central-finance-unit', 'PL1 2DP', 'South West'),
  ('devon-cornwall-fixed-penalty-office', 'PL1 2YN', 'South West'),
  ('doncaster-justice-centre-north', 'DN1 3HS', 'Yorkshire and the Humber'),
  ('doncaster-justice-centre-north', 'DN1 3HT', 'Yorkshire and the Humber'),
  ('doncaster-justice-centre-south', 'DN1 3HS', 'Yorkshire and the Humber'),
  ('doncaster-justice-centre-south', 'S3 8PH', 'Yorkshire and the Humber'),
  ('doncaster-regional-divorce-centre', 'DN1 3HS', 'Yorkshire and the Humber'),
  ('doncaster-social-security-and-child-support-tribunal', 'LS1 2ED', 'Yorkshire and the Humber'),
  ('doncaster-social-security-and-child-support-tribunal', 'DN1 3DF', 'Yorkshire and the Humber'),
  ('dorchester-crown-court', 'DT1 1XJ', 'South West'),
  ('dover-magistrates-court', 'CT16 1BS', 'South East'),
  ('dudley-county-court-and-family-court', 'DY1 1RY', 'West Midlands'),
  ('dudley-magistrates-court', 'DY1 1RY', 'West Midlands'),
  ('durham-county-court-and-family-court', 'DH1 3RG', 'North East'),
  ('durham-crown-court', 'DH1 3HW', 'North East'),
  ('durham-magistrates-court', 'DH1 3HW', 'North East'),
  ('durham-magistrates-court', 'DH3 3UA', 'North East'),
  ('durham-regional-divorce-centre', 'DH1 3RG', 'North East'),
  ('ealing-magistrates-court', 'NW10 2DZ', 'London'),
  ('ealing-magistrates-court', 'W13 0SD', 'London'),
  ('east-berkshire-magistrates-court-bracknell', 'SL1 2HJ', 'South East'),
  ('east-berkshire-magistrates-court-bracknell', 'RG12 1AE', 'South East'),
  ('east-berkshire-magistrates-court-maidenhead', 'SL6 8PB', 'South East'),
  ('east-berkshire-magistrates-court-maidenhead', 'RG1 7TQ', 'South East'),
  ('east-berkshire-magistrates-court-slough', 'SL1 2HJ', 'South East'),
  ('east-berkshire-magistrates-court-slough', 'RG1 7TQ', 'South East'),
  ('east-london-family-court', 'E14 4HD', 'London'),
  ('east-london-family-proceedings-court', 'E15 4SB', 'London'),
  ('east-london-tribunal-hearing-centre', 'E14 2BE', 'London'),
  ('east-midlands-regional-divorce-centre', 'NG2 9QN', 'East Midlands'),
  ('eastbourne-county-court-and-family-court', 'BN21 4UN', 'South East'),
  ('eastbourne-magistrates-court', 'BN21 4UN', 'South East'),
  ('edmonton-county-court-and-family-court', 'N18 2TN', 'London'),
  ('employment-appeal-tribunal-england-and-wales', 'EC4A 1NL', 'London'),
  ('enfield-social-security-and-child-support-tribunal', 'EN1 1TR', 'London'),
  ('enfield-social-security-and-child-support-tribunal', 'SM1 1DA', 'London'),
  ('epsom-social-security-and-child-support-tribunal', 'KT17 1HF', 'South East'),
  ('exeter-combined-court-centre', 'EX1 1UH', 'South West'),
  ('exeter-magistrates-court-north-and-east-devon', 'EX1 2LS', 'South West'),
  ('exeter-magistrates-court-north-and-east-devon', 'EX1 1UH', 'South West'),
  ('exeter-probate-sub-registry', 'CF24 0RZ ', 'South Wales Central'),
  ('family-division', 'WC2A 2LL', 'London'),
  ('fareham-magistrates-court', 'PO1 2DQ', 'South East'),
  ('fareham-magistrates-court', 'PO16 7SB', 'South East'),
  ('field-house-tribunal-hearing-centre', 'EC4A 1DZ', 'London'),
  ('fleetwood-family-court', 'FY1 5RJ', 'North West'),
  ('fleetwood-family-court', 'FY7 6BN', 'North West'),
  ('folkestone-magistrates-court', 'CT20 2DH', 'South East'),
  ('gangmaster-licensing-appeals-england-wales-and-scotland', 'M3 2JA', 'North West'),
  ('gateshead-county-court-and-family-court', 'NE8 1DT', 'North East'),
  ('gateshead-magistrates-court-and-family-court', 'NE8 1DT', 'North East'),
  ('general-regulatory-chamber', 'LE1 8DJ', 'East Midlands'),
  ('gloucester-and-cheltenham-county-and-family-court', 'GL1 2DE', 'South West'),
  ('gloucester-crown-court', 'GL1 2TS', 'South West'),
  ('gloucester-magistrates-court', 'GL1 2JH', 'South West'),
  ('gloucester-magistrates-court', 'GL1 2XG', 'South West'),
  ('gloucester-probate-sub-registry', 'OX1 1LY', 'South East'),
  ('gloucester-probate-sub-registry', 'GL1 2DG', 'South West'),
  ('grantham-magistrates-court', 'NG31 7SB', 'East Midlands'),
  ('grantham-magistrates-court', 'LN5 7QA', 'East Midlands'),
  ('great-grimsby-combined-court-centre', 'DN31 1HX', 'Yorkshire and the Humber'),
  ('great-yarmouth-magistrates-court-and-family-court', 'NR3 1UP', 'Eastern'),
  ('great-yarmouth-magistrates-court-and-family-court', 'NR30 1PW', 'Eastern'),
  ('greater-manchester-central-accounts-and-enforcement-unit', 'M61 0EQ', 'North West'),
  ('greater-manchester-central-accounts-and-enforcement-unit', 'M60 1PR', 'North West'),
  ('greenwich-magistrates-court', 'BR1 1RA', 'London'),
  ('grimsby-magistrates-court-and-family-court', 'DN31 1NH', 'Yorkshire and the Humber'),
  ('guildford-county-court-and-family-court', 'GU1 4PS', 'South East'),
  ('guildford-crown-court', 'GU1 4ST', 'South East'),
  ('guildford-magistrates-court-and-family-court', 'GU1 4PS', 'South East'),
  ('hammersmith-county-court', 'SW15 2SU', 'London'),
  ('hammersmith-magistrates-court', 'NW1 5BR', 'London'),
  ('hammersmith-magistrates-court', 'W6 8DN', 'London'),
  ('hampshire-the-isle-of-wight-fixed-penalty-office', 'SO23 7XF', 'South East'),
  ('harlow-social-security-and-child-support-tribunal', 'CM20 1HH', 'Eastern'),
  ('harlow-social-security-and-child-support-tribunal', 'B16 6FR', 'West Midlands'),
  ('harmondsworth-tribunal-hearing-centre', 'UB7 0HD', 'London'),
  ('harrogate-justice-centre', 'HG1 1EL', 'Yorkshire and the Humber'),
  ('harrow-crown-court', 'HA1 4TU', 'London'),
  ('hastings-county-court-and-family-court', 'TN34 1QX', 'South East'),
  ('hastings-magistrates-court', 'TN34 1ND', 'South East'),
  ('hatfield-magistrates-court', 'LU1 5BL', 'Eastern'),
  ('hatfield-magistrates-court', 'AL10 9SJ', 'Eastern'),
  ('hatton-cross-tribunal-hearing-centre', 'TW14 0LS', 'London'),
  ('havant-justice-centre', 'PO9 2AL', 'South East'),
  ('haverfordwest-county-court-and-family-court', 'SA61 2AX', 'Mid and West Wales'),
  ('haverfordwest-magistrates-court', 'SA61 2AX', 'Mid and West Wales'),
  ('hendon-magistrates-court', 'NW1 5BR', 'London'),
  ('hendon-magistrates-court', 'NW9 7BY', 'London'),
  ('hereford-county-court-and-family-court', 'WR1 1EQ', 'West Midlands'),
  ('hereford-county-court-and-family-court', 'HR1 2HE', 'West Midlands'),
  ('hereford-justice-centre', 'WR1 3QZ', 'West Midlands'),
  ('hereford-justice-centre', 'HR1 2HE', 'West Midlands'),
  ('hertford-county-court-and-family-court', 'SG14 1DF', 'Eastern'),
  ('hertford-county-court-and-family-court', 'SG13 9HT', 'Eastern'),
  ('hertford-magistrates-court-and-family-court', 'SG14 1DH', 'Eastern'),
  ('high-wycombe-county-court-and-family-court', 'HP11 1LR', 'South East'),
  ('high-wycombe-county-court-and-family-court', 'RG1 1HE', 'South East'),
  ('high-wycombe-magistrates-court-and-family-court', 'HP11 1LR', 'South East'),
  ('high-wycombe-magistrates-court-and-family-court', 'MK9 2AJ', 'South East'),
  ('highbury-corner-magistrates-court', 'N7 8JA', 'London'),
  ('highbury-corner-magistrates-court', 'N7 1AF', 'London'),
  ('hinckley-magistrates-court', 'LE1 6BT', 'East Midlands'),
  ('hmcts-wales-and-the-south-west-enforcement-contact-centre', 'SA13 1SB', 'South Wales West'),
  ('horsham-county-court-and-family-court', 'BN2 0RF', 'South East'),
  ('horsham-county-court-and-family-court', 'RH12 2ET', 'South East'),
  ('horsham-magistrates-court', 'RH12 2ET', 'South East'),
  ('horsham-magistrates-court', 'BN2 0LG', 'South East'),
  ('hove-trial-centre', 'BN3 3BN', 'South East'),
  ('hove-trial-centre', 'BN7 1YB', 'South East'),
  ('huddersfield-county-court-and-family-court', 'HD1 2RR', 'Yorkshire and the Humber'),
  ('hull-and-holderness-magistrates-court-and-hearing-centre', 'HU1 1RD', 'Yorkshire and the Humber'),
  ('hull-tribunal-hearing-centre', 'HU1 1UY', 'Yorkshire and the Humber'),
  ('huntingdon-law-courts', 'PE29 3DW', 'Eastern'),
  ('huntingdon-law-courts', 'PE1 1ED', 'Eastern'),
  ('inner-london-crown-court', 'SE1 6AZ', 'London'),
  ('inner-london-family-proceedings-court', 'W1A 3AE', 'London'),
  ('ipswich-county-court-and-family-hearing-centre', 'IP1 1EJ', 'Eastern'),
  ('ipswich-county-court-and-family-hearing-centre', 'NR3 1UR', 'Eastern'),
  ('ipswich-crown-court', 'IP1 2AG', 'Eastern'),
  ('ipswich-district-probate-registry', 'NE1 4DR', 'North East'),
  ('ipswich-magistrates-court', 'IP1 2AP', 'Eastern'),
  ('isle-of-wight-combined-court', 'PO30 5YT', 'South East'),
  ('isles-of-scilly-magistrates-court', 'TR21 0JD', 'South West'),
  ('isles-of-scilly-magistrates-court', 'PL31 2AL ', 'South West'),
  ('isleworth-crown-court', 'TW7 5LP', 'London'),
  ('kendal-county-court-and-family-court', 'LA9 4TJ', 'North West'),
  ('kendal-county-court-and-family-court', 'LA14 5QX', 'North West'),
  ('kendal-magistrates-court', 'LA9 4TJ', 'North West'),
  ('kendal-magistrates-court', 'LA14 5QX', 'North West'),
  ('kent-surrey-and-sussex-enforcement-business-centre', 'ME14 9PG', 'South East'),
  ('kettering-county-court', 'NN16 0BE', 'East Midlands'),
  ('kettering-county-court', 'NN1 3HQ', 'East Midlands'),
  ('kettering-magistrates-court', 'NN3 6AS', 'East Midlands'),
  ('kidderminster-magistrates-court', 'WR1 3QZ', 'West Midlands'),
  ('kidderminster-magistrates-court', 'DY10 1QQ', 'West Midlands'),
  ('kings-lynn-crown-court', 'PE30 1PQ', 'Eastern'),
  ('kings-lynn-magistrates-court-and-family-court', 'NR3 1UP', 'Eastern'),
  ('kings-lynn-magistrates-court-and-family-court', 'PE30 1PQ', 'Eastern'),
  ('kingston-upon-hull-combined-court-centre', 'HU1 2EZ', 'Yorkshire and the Humber'),
  ('kingston-upon-thames-county-court-and-family-court', 'KT1 2AD', 'London'),
  ('kingston-upon-thames-crown-court', 'KT1 2BB', 'London'),
  ('kirklees-huddersfield-magistrates-court-and-family-court', 'HD1 2NW', 'Yorkshire and the Humber'),
  ('kirklees-huddersfield-magistrates-court-and-family-court', 'HD1 2NH', 'Yorkshire and the Humber'),
  ('knutsford-crown-court', 'WA16 0PB', 'North West'),
  ('knutsford-crown-court', 'CH1 2AN', 'North West'),
  ('lambeth-county-court-and-family-court', 'SE11 4DZ', 'London'),
  ('lambeth-county-court-and-family-court', 'EC1V 3RE', 'London'),
  ('lancaster-courthouse', 'LA1 1XZ', 'North West'),
  ('lancaster-crown-court', 'LA1 1YJ', 'North West'),
  ('lancaster-crown-court', 'PR1 2LL', 'North West'),
  ('lancaster-magistrates-court', 'PR1 2QT', 'North West'),
  ('lancaster-magistrates-court', 'LA1 1XZ', 'North West'),
  ('lancaster-probate-sub-registry', 'L2 1XA', 'North West'),
  ('land-registration', 'WC1E 7LR', 'London'),
  ('lavender-hill-magistrates-court', 'SW11 1JU', 'London'),
  ('leamington-spa-magistrates-court', 'CV32 4EL', 'West Midlands'),
  ('leeds-combined-court-centre', 'LS1 3BG', 'Yorkshire and the Humber'),
  ('leeds-district-probate-registry', 'LS1 2BA', 'Yorkshire and the Humber'),
  ('leeds-district-probate-registry', 'LS1 2ED', 'Yorkshire and the Humber'),
  ('leeds-employment-tribunal', 'LS1 5ES', 'Yorkshire and the Humber'),
  ('leeds-magistrates-court-and-family-court', 'LS1 3BY', 'Yorkshire and the Humber'),
  ('leeds-magistrates-court-and-family-court', 'LS1 3JP', 'Yorkshire and the Humber'),
  ('leeds-social-security-and-child-support-tribunal', 'LS1 2ED', 'Yorkshire and the Humber'),
  ('leicester-county-court-and-family-court', 'LE1 6HG', 'East Midlands'),
  ('leicester-crown-court', 'LE1 6HG', 'East Midlands'),
  ('leicester-magistrates-court', 'LE1 6BT', 'East Midlands'),
  ('leicester-probate-sub-registry', 'OX1 1LY', 'South East'),
  ('leicester-probate-sub-registry', 'LE1 6HG', 'East Midlands'),
  ('leicester-tribunal-hearing-centre', 'LE1 6TE', 'East Midlands'),
  ('lewes-combined-court-centre', 'BN7 1YB', 'South East'),
  ('lewes-combined-court-centre', 'BN2 0RF', 'South East'),
  ('leyland-family-hearing-centre', 'PR25 2EX', 'North West'),
  ('leyland-family-hearing-centre', 'PR1 2PD', 'North West'),
  ('lincoln-county-court-and-family-court', 'LN5 7PS', 'East Midlands'),
  ('lincoln-crown-court', 'LN1 3GA', 'East Midlands'),
  ('lincoln-magistrates-court', 'LN5 7QA', 'East Midlands'),
  ('lincoln-probate-sub-registry', 'LS1 2BA', 'Yorkshire and the Humber'),
  ('liverpool-civil-and-family-court', 'L2 2BX', 'North West'),
  ('liverpool-crown-court', 'L2 1XA', 'North West'),
  ('liverpool-district-probate-registry', 'L2 1XA', 'North West'),
  ('liverpool-knowsley-magistrates-court', 'L2 1XA', 'North West'),
  ('liverpool-social-security-and-child-support-tribunal', 'L2 5UZ', 'North West'),
  ('liverpool-youth-court', 'L2 1XA', 'North West'),
  ('llandrindod-wells-magistrates-and-family-court', 'LD1 5DF', 'Mid and West Wales'),
  ('llandrindod-wells-magistrates-and-family-court', 'CF47 8BH', 'South Wales East'),
  ('llandudno-magistrates-court', 'LL30 1GA', 'North Wales'),
  ('llanelli-law-courts', 'SA15 3AW', 'Mid and West Wales'),
  ('london-centralised-legal-aid-office', 'RM1 3BH', 'London'),
  ('london-circuit-commercial-court', 'EC4A 1NL', 'London'),
  ('london-collection-and-compliance-centre', 'WC1A 9QD', 'London'),
  ('london-probate-department', 'WC1V 6NP', 'London'),
  ('london-south-employment-tribunal', 'CR0 2RF ', 'London'),
  ('loughborough-magistrates-court', 'LE11 1AZ', 'East Midlands'),
  ('loughborough-magistrates-court', 'LE1 6BT', 'East Midlands'),
  ('luton-and-south-bedfordshire-magistrates-court-and-family-court', 'LU1 5BL', 'Eastern'),
  ('luton-crown-court', 'LU1 2AA', 'Eastern'),
  ('luton-justice-centre', 'LU1 2LJ', 'Eastern'),
  ('maidstone-combined-court-centre', 'ME16 8EQ', 'South East'),
  ('maidstone-combined-court-centre', 'ME4 4JZ', 'South East'),
  ('maidstone-magistrates-court', 'ME15 6LL', 'South East'),
  ('maidstone-magistrates-court', 'ME4 4JZ', 'South East'),
  ('maidstone-probate-sub-registry', 'ME16 8EQ', 'South East'),
  ('maidstone-probate-sub-registry', 'BN2 0RF', 'South East'),
  ('maintenance-enforcement-business-centre-england', 'IP33 1TR', 'Eastern'),
  ('maintenance-enforcement-business-centre-wales', 'SA13 1SB', 'South Wales West'),
  ('maintenance-enforcement-centre-london', 'WC1V 6NP', 'London'),
  ('manchester-civil-justice-centre-civil-and-family-courts', 'M60 9DJ', 'North West'),
  ('manchester-crown-court-crown-square', 'M3 3FL', 'North West'),
  ('manchester-crown-court-minshull-st', 'M1 3FS', 'North West'),
  ('manchester-district-probate-registry', 'M60 9DJ', 'North West'),
  ('manchester-employment-tribunal', 'M3 2JA', 'North West'),
  ('manchester-magistrates-court', 'M60 1PR', 'North West'),
  ('manchester-tribunal-hearing-centre', 'M1 4AH', 'North West'),
  ('mansfield-magistrates-and-county-court', 'NG19 6EE', 'East Midlands'),
  ('margate-magistrates-court', 'CT9 1RL', 'South East'),
  ('margate-magistrates-court', 'CT20 2DH', 'South East'),
  ('mayors-and-city-of-london-court', 'EC2V 5AR', 'London'),
  ('medway-county-court-and-family-court', 'ME4 4JZ', 'South East'),
  ('medway-magistrates-court-and-family-court', 'ME4 4JZ', 'South East'),
  ('mental-health-tribunal', 'LE1 8BN ', 'East Midlands'),
  ('merthyr-tydfil-combined-court-centre', 'CF47 8BH', 'South Wales East'),
  ('mid-and-south-east-northumberland-law-courts', 'NE22 7LX', 'North East'),
  ('middlesbrough-county-court-at-teesside-combined-court', 'TS1 2AE', 'North East'),
  ('middlesbrough-probate-sub-registry', 'NE1 4DR', 'North East'),
  ('midlands-and-wales-regional-fixed-penalty-office', 'LE11 9HB', 'East Midlands'),
  ('midlands-eastemployment-tribunal', 'NG2 1EE', 'East Midlands'),
  ('midlands-west-employment-tribunal', 'B5 4UU', 'West Midlands'),
  ('milton-keynes-county-court-and-family-court', 'MK9 2DT', 'South East'),
  ('milton-keynes-magistrates-court-and-family-court', 'MK9 2AJ', 'South East'),
  ('mold-justice-centre', 'LL12 7BP', 'North Wales'),
  ('mold-justice-centre', 'CH7 1AE', 'North Wales'),
  ('money-claim-online-mcol', 'NN1 2LH', 'East Midlands'),
  ('morpeth-and-berwick-county-court-and-family-court', 'NE61 1LA', 'North East'),
  ('national-taxing-team-birmingham-office', 'B4 6LG', 'West Midlands'),
  ('national-taxing-team-manchester-office', 'M60 9DJ', 'North West'),
  ('newcastle-civil-family-courts-and-tribunals-centre', 'NE1 8QF', 'North East'),
  ('newcastle-district-probate-registry', 'NE1 4DR', 'North East'),
  ('newcastle-moot-hall', 'NE1 1RQ', 'North East'),
  ('newcastle-moot-hall', 'NE1 3LA', 'North East'),
  ('newcastle-social-security-and-child-support-tribunal', 'NE1 6PA', 'North East'),
  ('newcastle-upon-tyne-combined-court-centre', 'NE1 3LA', 'North East'),
  ('newcastle-upon-tyne-magistrates-court', 'NE1 6XA', 'North East'),
  ('newcastle-upon-tyne-magistrates-court', 'NE99 1AU', 'North East'),
  ('newport-south-wales-county-court-and-family-court', 'NP19 7AA', 'South Wales East'),
  ('newport-south-wales-crown-court', 'CF10 3PG', 'South Wales Central'),
  ('newport-south-wales-crown-court', 'NP20 4PR', 'South Wales East'),
  ('newport-south-wales-immigration-and-asylum-tribunal', 'NP18 2LX', 'South Wales East'),
  ('newport-south-wales-magistrates-court', 'NP20 2GE', 'South Wales East'),
  ('newport-south-wales-magistrates-court', 'NP20 4PR', 'South Wales East'),
  ('newport-south-wales-regional-divorce-centre', 'NP19 7AA', 'South Wales East'),
  ('newton-abbot-magistrates-court', 'TQ12 1LA ', 'South West'),
  ('newton-abbot-magistrates-court', 'TQ2 7AZ', 'South West'),
  ('newton-aycliffe-magistrates-court', 'DL5 5RT', 'North East'),
  ('north-avon-magistrates-court', 'BS37 4PY', 'South West'),
  ('north-east-regional-divorce-centre', 'BD1 1JA', 'Yorkshire and the Humber'),
  ('north-liverpool-community-justice-centre', 'L20 3XX', 'North West'),
  ('north-regional-fixed-penalty-office', 'LS27 1DN', 'Yorkshire and the Humber'),
  ('north-shields-county-court-and-family-court', 'NE29 6AR', 'North East'),
  ('north-somerset-magistrates-court', 'BS22 7BB', 'South West'),
  ('north-staffordshire-justice-centre', 'ST16 2QQ', 'West Midlands'),
  ('north-staffordshire-justice-centre', 'ST5 2AA', 'West Midlands'),
  ('north-tyneside-magistrates-court', 'NE30 1AG', 'North East'),
  ('north-west-regional-divorce-centre', 'L2 2BX', 'North West'),
  ('north-yorkshire-magistrates-courts-central-finance-unit', 'NE29 1DZ', 'North East'),
  ('northallerton-magistrates-court-and-family-court', 'DL7 8QZ', 'Yorkshire and the Humber'),
  ('northampton-crown-county-and-family-court', 'NN1 3HQ', 'East Midlands'),
  ('northampton-magistrates-court', 'NN1 3EB', 'East Midlands'),
  ('northampton-magistrates-court', 'NN3 6AS', 'East Midlands'),
  ('northampton-social-security-and-child-support-tribunal', 'B16 6FR', 'West Midlands'),
  ('northampton-social-security-and-child-support-tribunal', 'NN1 2LX', 'East Midlands'),
  ('northern-derbyshire-magistrates-court-and-family-court--2', 'S41 7TW', 'East Midlands'),
  ('northern-derbyshire-magistrates-court-and-family-court--2', 'DE1 2XE', 'East Midlands'),
  ('northern-derbyshire-magistrates-court-and-family-court--2', 'NG2 9QN ', 'East Midlands'),
  ('northern-derbyshire-magistrates-court-and-family-court', 'S41 7TW', 'East Midlands'),
  ('norwich-combined-court-centre', 'NR3 1UR', 'Eastern'),
  ('norwich-employment-tribunal', 'NR3 1UP', 'Eastern'),
  ('norwich-employment-tribunal', 'PE29 3DW', 'Eastern'),
  ('norwich-magistrates-court-and-family-court', 'NR3 1UP', 'Eastern'),
  ('norwich-probate-sub-registry', 'NE1 4DR', 'North East'),
  ('norwich-probate-sub-registry', 'NR3 1UR', 'Eastern'),
  ('norwich-social-security-and-child-support-tribunal', 'NR1 3PL', 'Eastern'),
  ('nottingham-county-court-and-family-court', 'NG1 7EJ', 'East Midlands'),
  ('nottingham-crown-court', 'NG1 7EL', 'East Midlands'),
  ('nottingham-magistrates-court', 'NG2 1EE', 'East Midlands'),
  ('nottingham-social-security-and-child-support-tribunal', 'B16 6FR', 'West Midlands'),
  ('nottingham-social-security-and-child-support-tribunal', 'NG1 7FG', 'East Midlands'),
  ('nuneaton-county-court', 'CV11 4WX', 'West Midlands'),
  ('nuneaton-county-court', 'CV11 4JU', 'West Midlands'),
  ('nuneaton-magistrates-court', 'CV11 4JU', 'West Midlands'),
  ('oldham-county-court-and-family-court', 'OL1 1NL', 'North West'),
  ('oldham-county-court-and-family-court', 'OL1 1NL', 'North West'),
  ('oxford-and-southern-oxfordshire-magistrates-court', 'OX1 1RZ', 'South East'),
  ('oxford-combined-court-centre', 'OX1 1TL', 'South East'),
  ('oxford-district-probate-registry', 'OX1 1LY', 'South East'),
  ('oxford-social-security-child-support-tribunal', 'OX2 9JU', 'South East'),
  ('patents-court', 'EC4A 1NL', 'London'),
  ('peterborough-combined-court-centre', 'PE1 1EJ', 'Eastern'),
  ('peterborough-magistrates-court', 'PE1 1ED', 'Eastern'),
  ('peterborough-probate-sub-registry', 'IP1 1EJ', 'Eastern'),
  ('peterborough-probate-sub-registry', 'PE1 1EJ', 'Eastern'),
  ('peterlee-magistrates-court', 'SR8 1QR', 'North East'),
  ('peterlee-magistrates-court', 'DL5 5RT', 'North East'),
  ('plymouth-combined-court', 'PL1 2ER', 'South West'),
  ('plymouth-magistrates-court', 'PL1 2DP', 'South West'),
  ('pocock-street-tribunal-hearing-centre', 'SE1 0BW', 'London'),
  ('pontypridd-county-court-and-family-court', 'CF37 1JR', 'South Wales Central'),
  ('poole-magistrates-court', 'BH15 2NS', 'South West'),
  ('poole-magistrates-court', 'BH7 7DS', 'South West'),
  ('port-talbot-justice-centre', 'SA13 1SB', 'South Wales West'),
  ('port-talbot-regional-divorce-centre', 'SA13 1SB', 'South Wales West'),
  ('portsmouth-combined-court-centre', 'PO1 2EB', 'South East'),
  ('portsmouth-magistrates-court', 'PO1 2DQ', 'South East'),
  ('prestatyn-justice-centre', 'LL19 7TE', 'North Wales'),
  ('preston-combined-court-centre', 'PR1 2LL', 'North West'),
  ('preston-crown-court-and-family-court-sessions-house', 'PR1 2PD', 'North West'),
  ('preston-magistrates-court', 'PR1 2QT', 'North West'),
  ('probate-service-centre', 'CM20 9QF', 'Eastern'),
  ('queens-bench-division', 'WC2A 2LL', 'London'),
  ('queens-bench-division', 'WC2A 2LL', 'London'),
  ('reading-county-court-and-family-court', 'RG1 1HE', 'South East'),
  ('reading-crown-court', 'RG1 3EH', 'South East'),
  ('reading-magistrates-court-and-family-court', 'RG1 7TQ', 'South East'),
  ('reading-tribunal-hearing-centre', 'WD17 1HP', 'Eastern'),
  ('reading-tribunal-hearing-centre', 'RG1 1DX', 'South East'),
  ('redditch-magistrates-court', 'WR1 3QZ', 'West Midlands'),
  ('redditch-magistrates-court', 'B98 8DB', 'West Midlands'),
  ('redhill-magistrates-court-and-family-court', 'RH1 6DH', 'South East'),
  ('redhill-magistrates-court-and-family-court', 'GU1 4AS', 'South East'),
  ('reedley-family-hearing-centre', 'BB1 6DJ', 'North West'),
  ('reedley-family-hearing-centre', 'BB10 2LJ', 'North West'),
  ('reigate-county-court-and-family-court', 'RH1 6BL', 'South East'),
  ('reigate-county-court-and-family-court', 'GU1 4PS', 'South East'),
  ('residential-property-eastern-region-first-tier-tribunal-property-chamber', 'CB1 1BA', 'Eastern'),
  ('residential-property-london-region-first-tier-tribunal-property-chamber', 'WC1E 7LR', 'London'),
  ('residential-property-midlands-region-first-tier-tribunal-property-chamber', 'B5 4UU ', 'West Midlands'),
  ('residential-property-northern-region-first-tier-tribunal-property-chamber', 'M1 4AH ', 'North West'),
  ('residential-property-southern-region-first-tier-tribunal-property-chamber', 'PO9 2AL', 'South East'),
  ('rhyl-county-court-and-family-court', 'LL18 3LA', 'North Wales'),
  ('richmond-upon-thames-magistrates-court', 'TW9 2RF', 'London'),
  ('richmond-upon-thames-magistrates-court', 'TW9 2RF', 'London'),
  ('rolls-building-business-and-property-courts-of-england-wales', 'EC4A 1NL', 'London'),
  ('romford-county-court-and-family-court', 'RM1 4DP', 'London'),
  ('romford-magistrates-court-formerly-havering-magistrates-court', 'RM1 3BH', 'London'),
  ('romford-magistrates-court-formerly-havering-magistrates-court', 'E3 4DJ', 'London'),
  ('royal-courts-of-justice', 'WC2A 2LL', 'London'),
  ('salisbury-law-courts', 'SP2 7EP', 'South West'),
  ('sandwell-magistrates-court', 'B69 4JN', 'West Midlands'),
  ('scarborough-justice-centre', 'YO12 7AE', 'Yorkshire and the Humber'),
  ('sefton-magistrates-court', 'L20 3XX', 'North West'),
  ('senior-courts-costs-office', 'WC2A 2LL', 'London'),
  ('sevenoaks-magistrates-court-and-family-court', 'TN13 2HU', 'South East'),
  ('sevenoaks-magistrates-court-and-family-court', 'ME4 4JZ', 'South East'),
  ('sheffield-combined-court-centre', 'S3 8PH', 'Yorkshire and the Humber'),
  ('sheffield-designated-family-court', 'S3 8PH', 'Yorkshire and the Humber'),
  ('sheffield-magistrates-court', 'S3 8LU', 'Yorkshire and the Humber'),
  ('sheffield-probate-sub-registry', 'S3 8PH', 'Yorkshire and the Humber'),
  ('sheffield-probate-sub-registry', 'LS1 2BA', 'Yorkshire and the Humber'),
  ('shrewsbury-crown-court', 'SY2 5NX', 'West Midlands'),
  ('shrewsbury-magistrates-court', 'TF3 4HX', 'West Midlands'),
  ('shrewsbury-magistrates-court', 'SY2 5NX', 'West Midlands'),
  ('skegness-magistrates-court', 'LN5 7QA', 'East Midlands'),
  ('skipton-county-court-and-family-court', 'BD23 1RH', 'Yorkshire and the Humber'),
  ('skipton-magistrates-court', 'HG1 1EL', 'Yorkshire and the Humber'),
  ('skipton-magistrates-court', 'BD23 1RH', 'Yorkshire and the Humber'),
  ('slough-county-court-and-family-court', 'RG1 1HE', 'South East'),
  ('slough-county-court-and-family-court', 'SL1 2HE', 'South East'),
  ('snaresbrook-crown-court', 'E11 1QW', 'London'),
  ('social-security-and-child-support-appeals-service-centre', 'CM20 9QF', 'Eastern'),
  ('solihull-magistrates-court', 'B4 6QA', 'West Midlands'),
  ('south-east-region-reciprocal-enforcement-unit', 'IP33 1HF', 'Eastern'),
  ('south-regional-fixed-penalty-office', 'SS2 6EU', 'Eastern'),
  ('south-tyneside-county-court-and-family-court', 'NE33 1RG', 'North East'),
  ('south-tyneside-magistrates-court', 'NE33 1RG', 'North East'),
  ('south-west-regional-divorce-centre', 'SO15 9GG', 'South East'),
  ('south-worcestershire-magistrates-court', 'WR1 3QZ', 'West Midlands'),
  ('southampton-combined-court-centre', 'SO15 2XQ', 'South East'),
  ('southend-county-court-and-family-court', 'SS2 6EU', 'Eastern'),
  ('southend-crown-court', 'SS2 6EG', 'Eastern'),
  ('southend-crown-court', 'SS14 2EW', 'Eastern'),
  ('southend-magistrates-court', 'CM1 9PZ', 'Eastern'),
  ('southend-magistrates-court', 'SS2 6EU', 'Eastern'),
  ('southport-magistrates-court', 'PR9 0LJ', 'North West'),
  ('southwark-crown-court', 'SE1 2HU', 'London'),
  ('spalding-magistrates-court', 'PE11 1BB', 'East Midlands'),
  ('spalding-magistrates-court', 'NG31 7SB', 'East Midlands'),
  ('special-educational-needs-and-disability-first-tier-tribunal', 'DL1 1ZD', 'North East'),
  ('st-albans-county-court', 'AL13JW', 'Eastern'),
  ('st-albans-county-court', 'AL1 3JW', 'Eastern'),
  ('st-albans-crown-court', 'AL1 3JW', 'Eastern'),
  ('st-albans-crown-court', 'LU1 2AA', 'Eastern'),
  ('st-albans-magistrates-court', 'LU1 5BL', 'Eastern'),
  ('st-albans-magistrates-court', 'AL1 3LB', 'Eastern'),
  ('st-helens-county-court-and-family-court', 'WA10 1SZ', 'North West'),
  ('stafford-combined-court-centre', 'ST16 2QQ', 'West Midlands'),
  ('staffordshire-central-finance-and-enforcement-unit', 'WS15 2FX', 'West Midlands'),
  ('staffordshire-magistrates-adminstration-team', 'ST16 2QQ', 'West Midlands'),
  ('staffordshire-magistrates-adminstration-team', 'ST16 2QQ', 'West Midlands'),
  ('staines-county-court-and-family-court', 'TW18 1XH', 'South East'),
  ('staines-county-court-and-family-court', 'GU1 4PS', 'South East'),
  ('staines-magistrates-court-and-family-court', 'GU1 4AS', 'South East'),
  ('staines-magistrates-court-and-family-court', 'TW18 1XH', 'South East'),
  ('stevenage-magistrates-court', 'LU1 5BL', 'Eastern'),
  ('stevenage-magistrates-court', 'SG1 1XH', 'Eastern'),
  ('stockport-county-court-and-family-court', 'SK1 3DQ', 'North West'),
  ('stockport-county-court-and-family-court', 'SK1 3NF', 'North West'),
  ('stockport-magistrates-court', 'SK1 3NF', 'North West'),
  ('stoke-on-trent-combined-court', 'ST1 3BP', 'West Midlands'),
  ('stoke-on-trent-probate-sub-registry', 'M60 1WJ', 'North West'),
  ('stourbridge-county-court', 'DY8 1QL', 'West Midlands'),
  ('stratford-housing-centre', 'E15 4SB', 'London'),
  ('stratford-magistrates-court', 'E15 4SB', 'London'),
  ('stratford-magistrates-court', 'E3 4DJ', 'London'),
  ('stroud-magistrates-court', 'GL5 1ET', 'South West'),
  ('stroud-magistrates-court', 'GL1 2XG', 'South West'),
  ('sunderland-county-family-magistrates-and-tribunal-hearings', 'SR1 3AP', 'North East'),
  ('surrey-fines-and-enforcement-unit', 'GU1 4GB', 'South East'),
  ('surrey-fixed-penalty-office', 'GU1 4GB', 'South East'),
  ('sussex-fines-enforcement-unit', 'BN2 0TF', 'South East'),
  ('sutton-social-security-and-child-support-tribunal', 'SM1 1DA', 'London'),
  ('swansea-civil-justice-centre', 'SA1 1SP', 'South Wales West'),
  ('swansea-crown-court', 'SA1 4PF', 'South Wales West'),
  ('swansea-magistrates-court', 'SA1 5DB', 'South Wales West'),
  ('swindon-combined-court', 'SN1 2HG', 'South West'),
  ('swindon-magistrates-court', 'SN1 2JB', 'South West'),
  ('swindon-magistrates-court', 'SN1 2HG', 'South West'),
  ('tameside-magistrates-court', 'OL6 7TP', 'North West'),
  ('taunton-crown-county-and-family-court', 'TA1 4EU', 'South West'),
  ('taunton-magistrates-court-tribunals-and-family-hearing-centre', 'TA1 4AX', 'South West'),
  ('tax-chamber-first-tier-tribunal', 'B16 6TZ', 'West Midlands'),
  ('taylor-house-tribunal-hearing-centre', 'EC1R 4QU', 'London'),
  ('technology-construction-court', 'EC4A 1NL', 'London'),
  ('teesside-combined-court-centre', 'TS1 2AE', 'North East'),
  ('teesside-magistrates-court', 'TS1 2AS', 'North East'),
  ('telford-county-court-and-family-court', 'TF3 4HX', 'West Midlands'),
  ('telford-magistrates-court', 'TF3 4HX', 'West Midlands'),
  ('telford-magistrates-court', 'ST16 2QQ', 'West Midlands'),
  ('thames-magistrates-court', 'E3 4DJ', 'London'),
  ('thanet-county-court-and-family-court', 'CT9 1RL', 'South East'),
  ('thanet-county-court-and-family-court', 'CT1 1ZA', 'South East'),
  ('torquay-and-newton-abbot-county-court-and-family-court', 'TQ2 7AZ', 'South West'),
  ('torquay-magistrates-court', 'TQ2 7AZ', 'South West'),
  ('torquay-magistrates-court', 'TQ1 4BP', 'South West'),
  ('tower-bridge-magistrates-court', 'SE5 7UP', 'London'),
  ('tower-bridge-magistrates-court', 'SE1 2JY', 'London'),
  ('traffic-enforcement-centre-tec', 'NN1 2LH', 'East Midlands'),
  ('truro-county-court-and-family-court', 'TR1 2PB', 'South West'),
  ('truro-crown-court', 'TR1 2PB', 'South West'),
  ('truro-magistrates-court', 'TR1 1HZ', 'South West'),
  ('truro-magistrates-court', 'PL31 2AL', 'South West'),
  ('tunbridge-wells-county-court-and-family-court', 'TN1 1DP', 'South East'),
  ('tunbridge-wells-county-court-and-family-court', 'TN1 1DP', 'South East'),
  ('upper-tribunal-administrative-appeals-chamber', 'EC4A 1NL', 'London'),
  ('upper-tribunal-lands-chamber', 'EC4A 1NL', 'London'),
  ('upper-tribunal-tax-and-chancery-chamber', 'EC4A 1NL', 'London'),
  ('uxbridge-county-court-and-family-court', 'UB4 8HL', 'London'),
  ('uxbridge-county-court-and-family-court', 'UB4 8HL', 'London'),
  ('uxbridge-magistrates-court', 'UB8 1PQ', 'London'),
  ('vale-of-glamorgan-magistrates-court', 'CF63 4SX', 'South Wales Central'),
  ('wakefield-civil-and-family-justice-centre', 'WF1 2QN', 'Yorkshire and the Humber'),
  ('wakefield-social-security-and-child-support-tribunal', 'LS1 2ED', 'Yorkshire and the Humber'),
  ('wakefield-social-security-and-child-support-tribunal', 'WF1 2TW', 'Yorkshire and the Humber'),
  ('wales-employment-tribunal', 'CF24 0RZ', 'South Wales Central'),
  ('wales-enforcement-office', 'SA13 1SB', 'South Wales West'),
  ('walsall-county-and-family-court', 'WS1 1JQ', 'West Midlands'),
  ('walsall-magistrates-court', 'WS2 8HA', 'West Midlands'),
  ('walsall-magistrates-court', 'DY1 1RY', 'West Midlands'),
  ('waltham-forest-magistrates-court', 'E3 4DJ', 'London'),
  ('waltham-forest-magistrates-court', 'E17 4NX', 'London'),
  ('wandsworth-county-court-and-family-court', 'SW15 2SU', 'London'),
  ('war-pensions-armed-forces-compensation-chamber', 'LE1 8FE', 'East Midlands'),
  ('warrington-crown-court', 'CH1 2AN', 'North West'),
  ('warrington-crown-court', 'WA1 1UR', 'North West'),
  ('warrington-magistrates-court', 'WA1 1UR', 'North West'),
  ('warwick-combined-court', 'CV32 4EL', 'West Midlands'),
  ('watford-county-court-and-family-court', 'WD17 1EZ', 'Eastern'),
  ('watford-magistrates-court-and-family-court', 'WD17 1EZ', 'Eastern'),
  ('watford-magistrates-court-and-family-court', 'WD17 1ST', 'Eastern'),
  ('watford-tribunal-hearing-centre', 'WD17 1HP', 'Eastern'),
  ('wellingborough-magistrates-court', 'NN8 1HF', 'East Midlands'),
  ('wellingborough-magistrates-court', 'NN3 6AS', 'East Midlands'),
  ('welshpool-magistrates-court', 'SY21 7UX', 'Mid and West Wales'),
  ('welshpool-magistrates-court', 'Ll12 7PB', 'North Wales'),
  ('west-berkshire-magistrates-court-newbury', 'RG14 5QS', 'South East'),
  ('west-berkshire-magistrates-court-newbury', 'RG1 7TQ', 'South East'),
  ('west-cumbria-courthouse', 'CA14 4AS', 'North West'),
  ('west-hampshire-magistrates-court', 'SO17 1EY', 'South East'),
  ('west-london-family-court', 'TW14 0LR', 'London'),
  ('west-midlands-regional-divorce-centre', 'ST5 2AA', 'West Midlands'),
  ('west-somerset-magistrates-court', 'TA1 4AX', 'South West'),
  ('west-yorkshire-enforcement-office', 'LS27 7ZT', 'Yorkshire and the Humber'),
  ('westminster-magistrates-court', 'NW1 5BR', 'London'),
  ('weston-super-mare-county-court-and-family-court', 'BS22 7BB', 'South West'),
  ('weymouth-and-dorchester-combined-court-centre', 'DT4 8BS', 'South West'),
  ('weymouth-combined-court', 'DT4 8BS', 'South West'),
  ('wigan-and-leigh-magistrates-court', 'WN1 1DW', 'North West'),
  ('wigan-county-court-and-family-court', 'WN1 1DW', 'North West'),
  ('willesden-county-court-and-family-court', 'NW10 8SB', 'London'),
  ('willesden-county-court-and-family-court', 'NW10 8SB', 'London'),
  ('willesden-magistrates-court', 'NW10 2DZ', 'London'),
  ('wimbledon-magistrates-court', 'SW19 7JP', 'London'),
  ('wimbledon-magistrates-court', 'SW 11 1JU', 'London'),
  ('winchester-combined-court-centre', 'SO23 9EL', 'South East'),
  ('winchester-district-probate-registry', 'SO23 9EL', 'South East'),
  ('wirral-magistrates-court', 'CH41 5HW', 'North West'),
  ('wolverhampton-combined-court-centre', 'WV1 3LQ', 'West Midlands'),
  ('wolverhampton-magistrates-court', 'WV1 1RA', 'West Midlands'),
  ('wolverhampton-magistrates-court', 'DY1 1RY', 'West Midlands'),
  ('wood-green-crown-court', 'N22 5LF', 'London'),
  ('woolwich-crown-court', 'SE28 0EY', 'London'),
  ('worcester-combined-court', 'WR1 1EQ', 'West Midlands'),
  ('worcester-justice-centre', 'WR1 3QZ', 'West Midlands'),
  ('worksop-magistrates-court', 'NG19 6EE', 'East Midlands'),
  ('worthing-county-court-and-family-court', 'BN11 1JD', 'South East'),
  ('worthing-magistrates-court', 'BN11 1JE', 'South East'),
  ('worthing-magistrates-court', 'BN2 0LG', 'South East'),
  ('wrexham-county-and-family-court', 'LL12 7BP', 'North Wales'),
  ('wrexham-magistrates-court', 'LL12 7BP', 'North Wales'),
  ('wrexham-magistrates-court', 'CH7 1AE', 'North Wales'),
  ('wrexham-regional-divorce-centre', 'LL12 7BP', 'North Wales'),
  ('yarls-wood-immigration-and-asylum-hearing-centre', 'MK44 1FD', 'Eastern'),
  ('yeovil-county-family-and-magistrates-court', 'BA20 1SW', 'South West'),
  ('york-county-court-and-family-court', 'YO1 9WL', 'Yorkshire and the Humber'),
  ('york-crown-court', 'YO1 9WZ', 'Yorkshire and the Humber'),
  ('york-magistrates-court-and-family-court', 'YO1 9RE', 'Yorkshire and the Humber'),
  ('york-probate-sub-registry', 'LS1 2BA', 'Yorkshire and the Humber');


ALTER TABLE public.search_courtaddress
  ADD COLUMN region_id integer;

UPDATE search_courtaddress AS ca
SET region_id = sr.id
  FROM temporary_table tt
         JOIN search_region sr on sr.name = tt.region
  JOIN search_courtaddress sc on tt.postcode = sc.postcode
WHERE ca.postcode = tt.postcode;

DROP table temporary_table;
